services:
  - type: web
    name: smart-healthcare-access
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: INTERNAL_API_KEY
        value: cyber-health-secure-2026
      - key: PORT
        value: 5000
